repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
    -   id: check
        name: check
        entry: make check
        language: python

    -   id: test
        name: test
        entry: make test
        language: python
